### ISSUE TITLE
KNOWN ISSUE: so return NaN passes the deleteFromDriverByKey test?

### ISSUE THREAD

**Issue by arye-eidelman** [learn-co-curriculum/js-data-structures-objects-lab#10]
```javascript
function deleteFromDriverByKey(driver, key){
  return NaN 
}
// why does this pass the test 
```

This is what I actually tried and it passed the test just fine without me realizing that it was actually returning `NaN`

```javascript
function deleteFromDriverByKey(driver, key){
  return driver - driver[key]  // NaN 
}
```

Only when I went to the next function and tried a similar answer which didn't work did I open up the debugger and realize that it was returning NaN 

```javascript
function destructivelyDeleteFromDriverByKey(driver, key){
  driver -= key
  return driver
}
```

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#11.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
