### ISSUE TITLE
please clarify readme 

### ISSUE THREAD

**Issue by joanrig** [learn-co-curriculum/js-data-structures-objects-lab#19]
pls drop a hint in the readme re: 

1. You can't pass this test with spread operator! You must use Object.assign({},driver).

2. you cannot use dot syntax for deleting key , you MUST use brackets.

**Comment by sgharms** [comment]
@joanrig 

1. We'll do better than that. We'll update the testing framework to love ES6. We're testing it now but it should land within the next day.

2. Added a hint.

Best,

Steven
