### ISSUE TITLE
Hint for the lab gives wrong format

### ISSUE THREAD

**Issue by jhharwood88** [learn-co-curriculum/js-data-structures-objects-lab#22]
The hint for the lab uses dot notation to reference the key, as well as the lesson before this teaching us how to non destructively use delete to remove a key. Using dot notation only satisfies one of the test conditions so when calling delete newObj.key it still fails for "1) deletes `key` from a clone of driver and returns the new driver (it is non-destructive)", only when using bracket notation does it actually satisfy the test. If this is intentional my apologies, but it seemed to me from the hint that dot notation is what is expected or at least suggested.

**Comment by maxwellbenton** [comment]
Hi @jhharwood88,

Thank you for spotting this and providing feedback. We've updated the hint in this lab to use bracket notation and cleaned up the readme content a little so this should not cause confusion for students going forward.

Thank you for contributing to a Learn.co lesson!
