### ISSUE TITLE
Before all hook timeout preventing all tests from being run (Mocha)

### ISSUE THREAD

**Issue by mackenzie-km** [learn-co-curriculum/js-data-structures-objects-lab#23]
1) "before all" hook

  0 passing (3s)
  1 failing

  1) "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at /Users/Mackenzie/js-data-structures-objects-lab-online-web-sp-000/node_modules/jsdom/lib/jsdom.js:325:18
      at processTicksAndRejections (internal/process/task_queues.js:82:9)

**Comment by mackenzie-km** [comment]
RESOLVED:

{
  "name": "js-data-structures-objects-lab",
  "version": "0.1.0",
  "description": "Learn.co's practice with manipulating JavaScript objects.",
  "main": "index.js",
  "scripts": {
    "test": "mocha -R mocha-multi --reporter-options spec=-,json=.results.json **--timeout 10000"**
  },

Please update the curriculum to have a longer timeout. I had to do a lot of google searching to get this lab to start! Glad it's working now.

**Comment by maxwellbenton** [comment]
Hi @mackenzie-km,

Thank you for providing this feedback. We've tested your suggested solution and incorporated it into this lesson to prevent this issue from occurring for future students. 

Thank you for contributing to a Learn lesson!
