### ISSUE TITLE
Capital D missing from destructivelyDeleteFromDriverByKey() 

### ISSUE THREAD

**Issue by yonureker** [learn-co-curriculum/js-data-structures-objects-lab#4]
The capital D of ...Driver... is missing from two instances of destructivelyDeleteFromdriverByKey. Added the code from IndexTest.js:

```describe(**destructivelyDeleteFromdriverByKey**(driver, key)', function () {
    it('returns driver without the delete key/value pair', function () {
      let newdriver = **destructivelyDeleteFromdriverByKey**(driver, 'name');

      expect(newdriver['name']).to.equal(undefined);
    });

    it('modifies the original driver', function () {
      let newdriver = destructivelyDeleteFromDriverByKey(driver, 'name');

      expect(driver['name']).to.equal(undefined);```

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
