### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by krdiamond** [learn-co-curriculum/js-data-structures-objects-lab#6]
I think there is a typo in the test. It says to call a function - "destructivelyDeleteFromdriverByKey" but it really means "destructivelyDeleteFromDriverByKey". The D in driver should be capitalized. The function needs to have the capital D to pass the test.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We corrected indexTest.js.

As always thank you for contributing!
