### ISSUE TITLE
typo in indexTest.js, line 17

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-data-structures-objects-lab#8]
an driver should be a driver
original should be original 

    it('returns an driver with the orignal key value pairs and the new key value pair', function () {
      expect(updateDriverWithKeyAndValue(driver, 'address', '11 Broadway')).to.eql({
        name: 'Sam',
        address: '11 Broadway'
      });
    });

**Comment by bruugey** [comment]
Fixed by commit c4a87e66caa006f82e9a256fa11184e5bb350a47.
